from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

PACKAGE_COPY_ENTRIES = [
    'README.md', 'requirements.txt', 'pyproject.toml', '.gitignore',
    'pi_agent_platform', 'config', 'scripts', 'deploy', 'containers', 'docs',
    'tests', 'vscode-extension', 'binaries', 'VERSION', 'VERSION_CURRENT.md',
    'FILES.txt', 'MANIFEST.json', 'docs-zed-mcp-example.json', 'install.sh', 'mcp',
]

_SKIP_DIR_NAMES = {'.git', '.venv', 'venv', 'node_modules', '__pycache__', 'dist'}
_SKIP_SUFFIXES = {'.pyc', '.pyo'}


def package_update_mode(package_root: Path) -> str:
    """Return the safe apply mode for an extracted PAC package.

    Full release zips generated by PAC contain MANIFEST.json and can replace
    known application roots. Iteration/changelog zips intentionally contain only
    touched files and a PAC_UPDATE_DIFF*.diff marker; those must be merged file
    by file or they can delete entire directories such as pi_agent_platform/.
    """
    root = Path(package_root)
    has_diff_marker = any(root.glob('PAC_UPDATE_DIFF*.diff'))
    has_manifest = (root / 'MANIFEST.json').is_file()
    if has_diff_marker and not has_manifest:
        return 'changed_files'
    return 'full_replace'


def describe_update_package(package_root: Path) -> dict[str, Any]:
    root = Path(package_root)
    files = [path for path in root.rglob('*') if path.is_file() and not _skip_path(path.relative_to(root))]
    mode = package_update_mode(root)
    diff_files = sorted(str(path.relative_to(root)) for path in root.glob('PAC_UPDATE_DIFF*.diff') if path.is_file())
    return {
        'update_mode': mode,
        'changed_file_count': len(files),
        'diff_files': diff_files,
        'has_manifest': (root / 'MANIFEST.json').is_file(),
    }


def copy_update_package_tree(src: Path, dst: Path) -> dict[str, Any]:
    mode = package_update_mode(src)
    if mode == 'changed_files':
        copied = merge_changed_files_tree(src, dst)
    else:
        copied = replace_full_package_tree(src, dst)
    return {'update_mode': mode, 'copied': copied, 'copied_count': len(copied)}


def replace_full_package_tree(src: Path, dst: Path) -> list[str]:
    copied: list[str] = []
    dst.mkdir(parents=True, exist_ok=True)
    for entry in PACKAGE_COPY_ENTRIES:
        source = src / entry
        if not source.exists():
            continue
        target = dst / entry
        if target.exists():
            if target.is_dir():
                shutil.rmtree(target)
            else:
                target.unlink()
        if source.is_dir():
            shutil.copytree(source, target, ignore=shutil.ignore_patterns('.venv', '__pycache__', '*.pyc'))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
        copied.append(entry)
    return copied


def merge_changed_files_tree(src: Path, dst: Path) -> list[str]:
    copied: list[str] = []
    root = Path(src)
    dst.mkdir(parents=True, exist_ok=True)
    for source in sorted(path for path in root.rglob('*') if path.is_file()):
        rel = source.relative_to(root)
        if _skip_path(rel):
            continue
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        copied.append(str(rel))
    return copied


def _skip_path(rel: Path) -> bool:
    parts = rel.parts
    if any(part in _SKIP_DIR_NAMES for part in parts[:-1]):
        return True
    return rel.suffix.lower() in _SKIP_SUFFIXES
